baseURL = 'https://pandincus.github.io/'
locale = 'en-us'
title = 'Traversing Roles'
theme = 'PaperMod'

paginate = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
  disableXML = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params]
  env = 'production'
  title = 'Traversing Roles'
  description = 'Screenshots, feelings, and other nonsense from my journey through gaming, and through life.'
  keywords = ['blog', 'gaming', 'journal']
  author = 'Dan'
  DateFormat = 'January 2, 2006'
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowToc = true
  TocOpen = false
  comments = true
  hidemeta = false

  [params.homeInfoParams]
    Title = "Hey, I'm Dan \U0001F44B"
    Content = "Welcome to my little blog, '__Traversing Roles__'. In this blog, I'll dump some personal thoughts about life, and also ramble about my passion for games of all kinds - tabletop, computer, board, whatever. I'm writing this mostly for myself, but please feel free to drop in and view my screenshots, feelings, in-character thoughts, whatever! And feel free to leave a comment, too."

  [params.giscus]
    repo = 'pandincus/pandincus.github.io'
    repoId = 'R_kgDOTmhqhA'
    category = 'Announcements'
    categoryId = 'DIC_kwDOTmhqM4DCMGw'
    mapping = 'pathname'
    strict = '0'
    reactionsEnabled = '0'
    emitMetadata = '0'
    inputPosition = 'top'
    lightTheme = 'light'
    darkTheme = 'dark'
    lang = 'en'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 20
  [[menu.main]]
    identifier = 'archive'
    name = 'Archive'
    url = '/archives/'
    weight = 30
